package io.madhu.txsimulator.constants;

public enum StoreType {

    Amazon,
    WALMART,
    TARGET,
    BEST_BUY,
    COSTCO,
    APPLE_STORE,
    HOME_DEPOT,
    STARBUCKS,
    MC_DONALDS,
    SUBWAY,
    NIKE,
    ADIDAS,
    IKEA,
    MACYS,
    KOHLS,
    SEPHORA,
    WALGREENS,
    CVS,
    SHELL,
    EXXONMOBIL,
    WHOLE_FOODS,
    TRADER_JOES,
    DOLLAR_GENERAL,
    PETS_MART,
    PETCO,
    LOWES,
    BARNES_NOBLE,
    TOYS_R_US,
    SPOTIFY,
    NETFLIX,
    HULU,
    DISNEY,
    XBOX_LIVE,
    PLAYSTATION_NETWORK,
    DICKS_SPORTING_GOODS,
    KAY_JEWELERS,
    JARED_GALLERIA_OF_JEWELRY;
}
