/**
 * Author: Madhu
 * User:madhu
 * Date:17/6/24
 * Time:7:18 PM
 * Project: user-creditcard-tx-simulator
 */

package io.madhu.txsimulator.constants;

public enum TransactionTypes {

    GROCERY_PURCHASE,
    FUEL_PURCHASE,
    RESTAURANT_PAYMENT,
    ONLINE_SHOPPING,
    UTILITY_BILL_PAYMENT,
    SUBSCRIPTION_PAYMENT,
    MOVIE_TICKET_PURCHASE,
    FLIGHT_TICKET_PURCHASE,
    HOTEL_BOOKING,
    CAR_RENTAL,
    CONCERT_TICKET_PURCHASE,
    GYM_MEMBERSHIP_PAYMENT,
    MEDICAL_BILL_PAYMENT,
    INSURANCE_PAYMENT,
    ELECTRONICS_PURCHASE,
    CLOTHING_PURCHASE,
    FURNITURE_PURCHASE,
    SCHOOL_FEE_PAYMENT,
    TUITION_FEE_PAYMENT,
    CASH_WITHDRAWAL,
    EMI_PAYMENT,
    GIFT_CARD_PURCHASE,
    CHARITY_DONATION,
    PARKING_FEE_PAYMENT,
    TOLL_PAYMENT,
    PET_SUPPLIES_PURCHASE,
    HOME_IMPROVEMENT,
    PHARMACY_PURCHASE,
    BOOK_PURCHASE,
    TOY_PURCHASE,
    MUSIC_STREAMING_SUBSCRIPTION,
    VIDEO_STREAMING_SUBSCRIPTION,
    GAMING_SUBSCRIPTION,
    SPORTING_GOODS_PURCHASE,
    JEWELRY_PURCHASE;
}
